package examen2p2_jesusrodriguez;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        leerArtistas();
        leerClient();
    }
    ArrayList<Cliente> client = new ArrayList();
    ArrayList<Artista> arti = new ArrayList();
    ArrayList<Lanzamiento> launch = new ArrayList();
    ArrayList<ListaRep> list = new ArrayList();
    ArrayList<Cancion> music= new ArrayList();
    ArrayList <Single> sin= new ArrayList();
    Artista artists;
    Cliente clien;
    ListaRep lists;
    AdminPB PBS;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        UserArtist = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AgeArtist = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PassArtist = new javax.swing.JTextField();
        CreateArtBt = new javax.swing.JButton();
        ArtNameTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        UserCL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AgeCl = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PasswordCl = new javax.swing.JTextField();
        CreateClient = new javax.swing.JButton();
        Artista = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        FechaLanz = new com.toedter.calendar.JDateChooser();
        CLanzBut = new javax.swing.JButton();
        NombreLanz = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        NombreLanzEdt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        FechaLanzEDT = new com.toedter.calendar.JDateChooser();
        CLanzEDT = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        CBEVT = new javax.swing.JComboBox<>();
        DELETELaun = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        AlbumName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ChooserFecha = new com.toedter.calendar.JDateChooser();
        CrearAlbum = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        SingleName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ChooserFecha1 = new com.toedter.calendar.JDateChooser();
        CrearSingle = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        CanName = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        DuraCan = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        CreateCan = new javax.swing.JButton();
        JBAL = new javax.swing.JComboBox<>();
        JBSIN = new javax.swing.JComboBox<>();
        RBAL = new javax.swing.JRadioButton();
        SNRB = new javax.swing.JRadioButton();
        Clientes = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        ButtonCreateList = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        ListaRepName = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        ListaNombreNueva = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaSongs = new javax.swing.JList<>();
        CBL = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        EliminarRep = new javax.swing.JButton();
        ModificarRep = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        PBC = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UsernameLog = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        PasswordLog = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TypeUserCB = new javax.swing.JComboBox<>();
        Registrar = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(102, 51, 0));

        jPanel4.setBackground(new java.awt.Color(102, 102, 0));

        jLabel8.setText("Username");

        jLabel9.setText("Age");

        jLabel10.setText("Password");

        CreateArtBt.setText("Create Artist");
        CreateArtBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateArtBtMouseClicked(evt);
            }
        });
        CreateArtBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateArtBtActionPerformed(evt);
            }
        });

        jLabel11.setText("Artistic Name");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArtNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(CreateArtBt, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ArtNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgeArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PassArtist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(CreateArtBt, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Artista", jPanel4);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Username");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 97, 31));
        jPanel3.add(UserCL, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 43, 141, -1));

        jLabel6.setText("Age");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 97, 31));
        jPanel3.add(AgeCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 109, 141, -1));

        jLabel7.setText("Password");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 137, 97, 31));
        jPanel3.add(PasswordCl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 174, 141, -1));

        CreateClient.setText("Create Client");
        CreateClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateClientMouseClicked(evt);
            }
        });
        CreateClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateClientActionPerformed(evt);
            }
        });
        jPanel3.add(CreateClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 310, 220));

        jTabbedPane1.addTab("Crear Cliente", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RegisterLayout = new javax.swing.GroupLayout(Register.getContentPane());
        Register.getContentPane().setLayout(RegisterLayout);
        RegisterLayout.setHorizontalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RegisterLayout.setVerticalGroup(
            RegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(102, 0, 102));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel12.setText("Nombre");

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel13.setText("Fecha de Lanzamiento");

        CLanzBut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CLanzBut.setText("CREAR LANZAMIENTO");
        CLanzBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLanzButMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CLanzBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreLanz, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FechaLanz, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 262, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreLanz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(FechaLanz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(CLanzBut, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Crear Lanzamiento", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Publicar Lanzamiento", jPanel7);

        jPanel9.setBackground(new java.awt.Color(102, 204, 0));

        jLabel14.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel14.setText("Evento");

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel15.setText("Fecha de Lanzamiento");

        CLanzEDT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CLanzEDT.setText("CREAR LANZAMIENTO");
        CLanzEDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLanzEDTMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel16.setText("Nombre");

        CBEVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DELETELaun.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DELETELaun.setText("ELIMINAR LANZAMIENTO");
        DELETELaun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETELaunMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBEVT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FechaLanzEDT, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NombreLanzEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(CLanzEDT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(DELETELaun)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBEVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreLanzEdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaLanzEDT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DELETELaun, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(CLanzEDT, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        jTabbedPane2.addTab("Editar/Eliminar Lanzamiento", jPanel9);

        jPanel10.setBackground(new java.awt.Color(102, 0, 0));
        jPanel10.setForeground(new java.awt.Color(102, 51, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("Fecha Lanzamiento");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 82, -1, -1));
        jPanel10.add(AlbumName, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 41, 173, -1));

        jLabel21.setText("Titulo Album");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 19, -1, -1));
        jPanel10.add(ChooserFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 116, 173, -1));

        CrearAlbum.setText("Crear Album");
        CrearAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearAlbumMouseClicked(evt);
            }
        });
        jPanel10.add(CrearAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 41, 260, 150));

        jTabbedPane2.addTab("Crear Album", jPanel10);

        jPanel13.setBackground(new java.awt.Color(51, 0, 51));
        jPanel13.setForeground(new java.awt.Color(204, 102, 0));

        jLabel22.setText("Fecha Lanzamiento");

        jLabel23.setText("Titulo Single");

        CrearSingle.setText("Crear Single");
        CrearSingle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearSingleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SingleName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)
                                .addComponent(ChooserFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(114, 114, 114)
                            .addComponent(CrearSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel23)
                    .addGap(6, 6, 6)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addComponent(SingleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addComponent(jLabel22)
                            .addGap(18, 18, 18)
                            .addComponent(ChooserFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(CrearSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Crear Single", jPanel13);

        jPanel15.setBackground(new java.awt.Color(0, 51, 51));

        jLabel24.setText("Titulo Cancion");

        jLabel25.setText("Duracion Cancion");

        jLabel26.setText("Referencia");

        CreateCan.setText("CREAR CANCION");
        CreateCan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateCanMouseClicked(evt);
            }
        });

        RBAL.setText("Album");

        SNRB.setText("Single");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25)
                                    .addComponent(DuraCan, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addComponent(CanName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(RBAL)
                            .addComponent(JBAL, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addComponent(CreateCan, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBSIN, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SNRB))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(CreateCan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel24)
                .addGap(6, 6, 6)
                .addComponent(CanName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGap(6, 6, 6)
                .addComponent(DuraCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(12, 12, 12)
                .addComponent(RBAL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(SNRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBSIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane2.addTab("Crear Cancion", jPanel15);

        jPanel5.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 700, 410));

        javax.swing.GroupLayout ArtistaLayout = new javax.swing.GroupLayout(Artista.getContentPane());
        Artista.getContentPane().setLayout(ArtistaLayout);
        ArtistaLayout.setHorizontalGroup(
            ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
        );
        ArtistaLayout.setVerticalGroup(
            ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(51, 102, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 51, 102));

        ButtonCreateList.setText("CREAR LISTA");
        ButtonCreateList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCreateListMouseClicked(evt);
            }
        });
        ButtonCreateList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCreateListActionPerformed(evt);
            }
        });

        jLabel17.setText("Nombre de la Lista");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel17))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ListaRepName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonCreateList, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListaRepName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonCreateList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jTabbedPane3.addTab("Crear Lista de Reproduccion", jPanel11);

        ListaSongs.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaSongs);

        CBL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBLItemStateChanged(evt);
            }
        });

        jLabel18.setText("Nombre Lista Nueva");

        EliminarRep.setText("Eliminar Lista de Reproduccion");
        EliminarRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarRepMouseClicked(evt);
            }
        });

        ModificarRep.setText("Modificar Lista de Reproduccion");
        ModificarRep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarRepMouseClicked(evt);
            }
        });

        jLabel19.setText("Lista de Reproduccion Actual");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(EliminarRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBL, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListaNombreNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(ModificarRep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(ListaNombreNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBL, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(EliminarRep, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModificarRep, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Editar/Eliminar Listas", jPanel12);

        jPanel14.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Visualizar Listas", jPanel14);

        jPanel16.setBackground(new java.awt.Color(102, 0, 0));

        jButton1.setText("PLAY");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel27.setText("Cancion");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PBC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(PBC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Reproducir Cancion", jPanel16);

        jPanel8.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 710, 380));

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes.getContentPane());
        Clientes.getContentPane().setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Type of user");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));
        jPanel1.add(UsernameLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 446, 32));

        LoginButton.setBackground(new java.awt.Color(0, 0, 0));
        LoginButton.setText("Login");
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });
        jPanel1.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 164, 86));
        jPanel1.add(PasswordLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 446, 32));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        TypeUserCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Artist", "Client" }));
        jPanel1.add(TypeUserCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 450, 40));

        Registrar.setBackground(new java.awt.Color(0, 0, 0));
        Registrar.setText("Register");
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 180, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        if (UsernameLog.getText().isEmpty() || PasswordLog.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los datos no estan completos");
        } else if (TypeUserCB.getSelectedIndex() == 0) {
            for (Artista a : arti) {
                if (a.getUsername().equals(UsernameLog.getText()) && a.getPassword().equals(PasswordLog.getText())) {
                      artists= a;
                    Artista.pack();
                    Artista.setModal(true);
                    Artista.setLocationRelativeTo(this);
                    Artista.setVisible(true);
                    UsernameLog.setText("");
                    PasswordLog.setText("");
                   

                }

            }
        } else if (TypeUserCB.getSelectedIndex() == 1) {
            for (Cliente c : client) {
                if (c.getUsername().equals(UsernameLog.getText()) && c.getPassword().equals(PasswordLog.getText())) {
                    clien= c;
                    Clientes.pack();
                    Clientes.setModal(true); 
                    Clientes.setLocationRelativeTo(this);
                    Clientes.setVisible(true);
                    UsernameLog.setText("");
                    PasswordLog.setText("");
                 
                }
            }

        }else{
            JOptionPane.showMessageDialog(this, "No valido");
        }


    }//GEN-LAST:event_LoginButtonMouseClicked

    private void RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseClicked
        Register.pack();
        Register.setModal(true);
        Register.setLocationRelativeTo(this);
        Register.setVisible(true);
    }//GEN-LAST:event_RegistrarMouseClicked

    private void CreateClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateClientMouseClicked
        if (UserCL.getText().isEmpty() || AgeCl.getText().isEmpty() || PasswordCl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(Register, "Algun o varios requisitos esta vacios");
        } else {
            String user = UserCL.getText();
            int age = Integer.parseInt(AgeCl.getText());
            String passw = PasswordCl.getText();
            boolean chris = false;

            if (age < 12) {
                JOptionPane.showMessageDialog(Register, "Your age should be 12 or older");
            } else {
                for (Cliente cliente : client) {
                    if (cliente.getUsername().equals(user)) {

                        chris = true;
                        break;
                    }
                }
                if (!chris) {
                    client.add(new Cliente("Client", user, passw, age));
                    actCliente();
                    bitacora(user, "Cliente");
                    JOptionPane.showMessageDialog(Register, "Your User has been created");
                    UserCL.setText("");
                    AgeCl.setText("");
                    PasswordCl.setText("");
                } else {
                    JOptionPane.showMessageDialog(Register, "This user exists");
                }

            }

        }


    }//GEN-LAST:event_CreateClientMouseClicked

    private void CreateArtBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateArtBtMouseClicked
        if (UserArtist.getText().isEmpty() || PassArtist.getText().isEmpty() || AgeArtist.getText().isEmpty() || ArtNameTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(Register, "Algun o varios requisitos estan vacios");
        } else {
            String user = UserArtist.getText();
            String pass = PassArtist.getText();
            int age = Integer.parseInt(AgeArtist.getText());
            String nom = ArtNameTxt.getText();
            boolean chris = false;

            if (age < 18) {
                JOptionPane.showMessageDialog(Register, "Your age should be 18 or older");
            } else {
                for (Artista artista : arti) {
                    if (artista.getUsername().equals(user)) {

                        chris = true;
                        break;
                    }
                }
                if (!chris) {
                    arti.add(new Artista(nom, "Artist", user, pass, age));
                    actArtistas();
                    bitacora(user, "Artista");
                    JOptionPane.showMessageDialog(Register, "Your User has been created");
                    UserArtist.setText("");
                    AgeArtist.setText("");
                    PassArtist.setText("");
                    ArtNameTxt.setText("");
                } else {
                    JOptionPane.showMessageDialog(Register, "This user exists");
                }
            }

        }


    }//GEN-LAST:event_CreateArtBtMouseClicked

    private void CreateArtBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateArtBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateArtBtActionPerformed

    private void CreateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateClientActionPerformed

    private void CLanzButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLanzButMouseClicked
        if (NombreLanz.getText().isEmpty()) {
            JOptionPane.showMessageDialog(Artista, "El nombre del lanzamiento esta vacio");
        } else {
            String name = NombreLanz.getText();
            Date fecha = FechaLanz.getDate();
            actArtistas();
            launch.add(new Lanzamiento(name, 0, fecha));
            CBEVT.setModel(actualizarcbLaunch());
            JOptionPane.showMessageDialog(Artista, "Lanzamiento creado exitosamente");
            NombreLanz.setText("");
        }
    }//GEN-LAST:event_CLanzButMouseClicked

    private void CLanzEDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLanzEDTMouseClicked
        if (NombreLanz.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Esta vacio para modificar");
        } else {
            String namenew = NombreLanzEdt.getText();
            actArtistas();
            Date fechanew = FechaLanzEDT.getDate();
            artists.getAl().get(CBEVT.getSelectedIndex()).setNombre(namenew);
            artists.getAl().get(CBEVT.getSelectedIndex()).setFecha(fechanew);
            JOptionPane.showMessageDialog(null, "Lanzamiento modificado");
        }
    }//GEN-LAST:event_CLanzEDTMouseClicked

    private void ButtonCreateListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCreateListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCreateListActionPerformed

    private void ButtonCreateListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCreateListMouseClicked
        if (ListaRepName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No le ha puesto nombre a su lista");
        } else {
            String tit = ListaRepName.getText();
            
            list.add(new ListaRep(tit, 0));
            actCliente();
           CBL.setModel(actualizarcbListasRP()); 
            JOptionPane.showMessageDialog(Clientes, "La Lista de Reproduccion ha sido creada");;
        }


    }//GEN-LAST:event_ButtonCreateListMouseClicked

    private void DELETELaunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETELaunMouseClicked
        arti.remove(CBEVT.getSelectedIndex());
        actualizarcbLaunch();
        JOptionPane.showMessageDialog(null, "El Lanzamiento ha sido eliminado");
            
        
                

        
        
        
        
    }//GEN-LAST:event_DELETELaunMouseClicked

    private void EliminarRepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarRepMouseClicked
        list.remove(CBL.getSelectedIndex());
        CBL.setModel(actualizarcbListasRP());
        JOptionPane.showMessageDialog(this, "La lista ha sido eliminada exitosamente");
        
        
        
    }//GEN-LAST:event_EliminarRepMouseClicked

    private void ModificarRepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarRepMouseClicked
      
       if (ListaNombreNueva.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Esta vacio para modificar");
        } else {
            String namenew = ListaNombreNueva.getText();

       
            //lists.getName();
            
            JOptionPane.showMessageDialog(null, "Lanzamiento modificado");
        }
       
       
    }//GEN-LAST:event_ModificarRepMouseClicked

    private void CBLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBLItemStateChanged
       if (CBL.getSelectedIndex()>=0) {
            ListaSongs.setModel(Actualizarl());
        }
    }//GEN-LAST:event_CBLItemStateChanged

    private void CrearAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearAlbumMouseClicked
        if (AlbumName.getText().isEmpty()) {
         JOptionPane.showMessageDialog(this,"Album no tiene nombre" );
        }else{
            arti.get(arti.indexOf(artists)).getAl().add(new Album(AlbumName.getText(), 0, ChooserFecha.getDate()));
          JBAL.setModel(actualizarcbal());
          JOptionPane.showMessageDialog(null, "Album Creado");
            AlbumName.setText("");

        }
    }//GEN-LAST:event_CrearAlbumMouseClicked

    private void CrearSingleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearSingleMouseClicked
        if (SingleName.getText().isEmpty()) {
         JOptionPane.showMessageDialog(this,"El Single no tiene nombre" );
        }else{
            arti.get(arti.indexOf(artists)).getCan().add(new Single(SingleName.getText(), 0, ChooserFecha1.getDate()));
            JBSIN.setModel(actualizarcbsin());
              JOptionPane.showMessageDialog(null, "Single Creado");
            SingleName.setText("");
        }
    }//GEN-LAST:event_CrearSingleMouseClicked

    private void CreateCanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateCanMouseClicked
        if (CanName.getText().isEmpty()||DuraCan.getText().isEmpty()) {
         JOptionPane.showMessageDialog(this,"La Cancion no tiene nombre" );
        }else{
            String titulo= CanName.getText();
            int dura= Integer.parseInt(DuraCan.getText());
            if (RBAL.isSelected()) {
                music.add(new Cancion(titulo, dura, (Album)JBAL.getSelectedItem()));
            }else if (SNRB.isSelected()) {
                music.add(new Cancion(titulo, dura, (Single)JBSIN.getSelectedItem()));
            }
            music.add(new Cancion());
            
            SingleName.setText("");
        }
    }//GEN-LAST:event_CreateCanMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    PBS= new AdminPB(PBC, 0, jPanel1);
    PBC.setMaximum(7);
    PBS.setVive(true);
    PBS.setTiempo(6);
    PBS.start();
    
    }//GEN-LAST:event_jButton1MouseClicked

    public DefaultComboBoxModel actualizarcbLaunch() {
        DefaultComboBoxModel MODEL = new DefaultComboBoxModel();
        for (Lanzamiento launches : launch) {
            MODEL.addElement(launches);

        }
        return MODEL;
    }
    
    
    
    
     public DefaultComboBoxModel actualizarcbListasRP() {
        DefaultComboBoxModel MODEL = new DefaultComboBoxModel();
        for (ListaRep lista : list) {
            MODEL.addElement(list);

        }
        return MODEL;
    }
     
     public DefaultComboBoxModel actualizarcbal() {
        DefaultComboBoxModel MODEL = new DefaultComboBoxModel();
        for (Album al: arti.get(arti.indexOf(artists)).getAl()) {
            MODEL.addElement(list);

        }
        return MODEL;
    }
     
       public DefaultComboBoxModel actualizarcbsin() {
        DefaultComboBoxModel MODEL = new DefaultComboBoxModel();
        for (Single single: arti.get(arti.indexOf(artists)).getCan()) {
            MODEL.addElement(list);

        }
        return MODEL;
    }
     
     
     
     
     

    private void actArtistas() {
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            File fichero = new File("./artistas.usr");
            fw = new FileOutputStream(fichero);
            bw = new ObjectOutputStream(fw);
            bw.writeObject(arti);
            bw.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }

    private void leerArtistas() {
        File fichero = new File("./artistas.usr");
        FileInputStream entrada = null;
        ObjectInputStream objeto = null;
        if (fichero.exists()) {
            try {
                entrada = new FileInputStream(fichero);
                objeto = new ObjectInputStream(entrada);
                arti = (ArrayList<Artista>) objeto.readObject();
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                objeto.close();
                entrada.close();
            } catch (IOException ex) {
            }
        }
    }

    private void actCliente() {
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            File fichero = new File("./Client.cl");
            fw = new FileOutputStream(fichero);
            bw = new ObjectOutputStream(fw);
            bw.writeObject(client);
            bw.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            bw.close();
            fw.close();
        } catch (IOException ex) {
        }
    }

    private void leerClient() {
        File fichero = new File("./Client.cl");
        FileInputStream entrada = null;
        ObjectInputStream objeto = null;
        if (fichero.exists()) {
            try {
                entrada = new FileInputStream(fichero);
                objeto = new ObjectInputStream(entrada);
                client = (ArrayList<Cliente>) objeto.readObject();
            } catch (Exception e) {
                e.printStackTrace();
            }
            try {
                objeto.close();
                entrada.close();
            } catch (IOException ex) {
            }
        }
    }

    private void bitacora(String usuario, String tipo) {
        File fichero = new File("./bitacora.txt");
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter(fichero, true);
            bw = new BufferedWriter(fw);
            bw.write("El usuario: " + usuario + ". siendo : " + tipo + ", se ha creado un : " + new Date().toString());
            bw.flush();
        } catch (Exception e) {
        }
        try {
            fw.close();
            bw.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    
    public DefaultListModel Actualizarl(){
        DefaultListModel model= new DefaultListModel();
        for (ListaRep listaRep : list) {
            model.addAll(list);
        }
        return model;
    }
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeArtist;
    private javax.swing.JTextField AgeCl;
    private javax.swing.JTextField AlbumName;
    private javax.swing.JTextField ArtNameTxt;
    private javax.swing.JDialog Artista;
    private javax.swing.JButton ButtonCreateList;
    private javax.swing.JComboBox<String> CBEVT;
    private javax.swing.JComboBox<String> CBL;
    private javax.swing.JButton CLanzBut;
    private javax.swing.JButton CLanzEDT;
    private javax.swing.JTextField CanName;
    private com.toedter.calendar.JDateChooser ChooserFecha;
    private com.toedter.calendar.JDateChooser ChooserFecha1;
    private javax.swing.JDialog Clientes;
    private javax.swing.JButton CrearAlbum;
    private javax.swing.JButton CrearSingle;
    private javax.swing.JButton CreateArtBt;
    private javax.swing.JButton CreateCan;
    private javax.swing.JButton CreateClient;
    private javax.swing.JButton DELETELaun;
    private javax.swing.JTextField DuraCan;
    private javax.swing.JButton EliminarRep;
    private com.toedter.calendar.JDateChooser FechaLanz;
    private com.toedter.calendar.JDateChooser FechaLanzEDT;
    private javax.swing.JComboBox<String> JBAL;
    private javax.swing.JComboBox<String> JBSIN;
    private javax.swing.JTextField ListaNombreNueva;
    private javax.swing.JTextField ListaRepName;
    private javax.swing.JList<String> ListaSongs;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton ModificarRep;
    private javax.swing.JTextField NombreLanz;
    private javax.swing.JTextField NombreLanzEdt;
    private javax.swing.JProgressBar PBC;
    private javax.swing.JTextField PassArtist;
    private javax.swing.JTextField PasswordCl;
    private javax.swing.JTextField PasswordLog;
    private javax.swing.JRadioButton RBAL;
    private javax.swing.JDialog Register;
    private javax.swing.JButton Registrar;
    private javax.swing.JRadioButton SNRB;
    private javax.swing.JTextField SingleName;
    private javax.swing.JComboBox<String> TypeUserCB;
    private javax.swing.JTextField UserArtist;
    private javax.swing.JTextField UserCL;
    private javax.swing.JTextField UsernameLog;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
